### ISSUE TITLE
row replacement error

### ISSUE THREAD

**Issue by Lakens** [yilinandrewang/pwrSEM#3]
Default settings, running simulation: App crashes at the end of the simulation.

 lavaan WARNING: some regression coefficients are unspecified and will be set to zero
Warning: Error in $<-.data.frame: replacement has 100 rows, data has 0

**Comment by yilinandrewang** [comment]
Will look into the error handling on this as well! When I tested this particular sequence prior to launch, the app only shows warning messages, so it is curious that the app is crashing now instead. I will keep you posted once I find a solution.

**Comment by yilinandrewang** [comment]
I updated the app such that it now displays error messages if either the population model for simulations is not fully identified or no target effect is selected. The crash in the previous version of the app happened because no population model was identified for simulations (hence its corresponding data frame had 0 row). Now the app does not allow users to run the simulations without having a valid population model in place, and the error messages show users what is missing.
